### PR TITLE
bug where nginx default site is being created even when 'default_site…

### PR DESCRIPTION
**Pull request by jbsmith86**
…_enabled' is set to false

---

This change is [Reviewable](https://reviewable.io/reviews/miketheman/nginx/413)

### CODE REVIEW

**Comment by tas50** [comment]
This sort of 1/2 fixes the problem. We shouldn't be templating the file if the site isn't enabled so that part is great, but if we don't want the site to be enabled we should be passing the false to the nginx_site resource so it actually disables the default site. You could take the same if statement you added and use it as an only_if on the template resource. That would still allow the attribute to properly disable the site, but also prevent the default site from being templated when set to false.

**Comment by jbsmith86** [comment]
that makes sense

**Comment by alexandrezia** [comment]
Try:

`nginx_site '000-default' do
  enable false
end`

**Comment by tas50** [comment]
Thanks for opening this PR. With the merge of the chef_nginx codebase back into the nginx cookbook I believe it’s no longer necessary. I’m going to close this out now, and I hope you can check out the massive changes that landed on master here https://github.com/chef-cookbooks/nginx/pull/435

**Pull request closed without merging**
