### PR TITLE
new feature: streams

### PR DESCRIPTION
**Pull request by DavidSie**
### Description
Added support of streams.

### Issues Resolved

this resolve issue of adding new stream to sites-enabled. streams has to appear as a top level object rather than in http directive

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by DavidSie** [comment]
Test failure do not seem related.

**Comment by majormoses** [comment]
It looks like you added installing `lib64z1-dev` and then removed it, did you try installing `zlib1g` instead? I tried it locally in vagrant and it worked.

```
$ git diff
diff --git a/Gemfile b/Gemfile
index c3bc0d1..8fe95f2 100644
--- a/Gemfile
+++ b/Gemfile
@@ -6,5 +6,9 @@
 
 source 'https://rubygems.org'
 
+gem 'berkshelf'
 gem 'stove'
+gem 'test-kitchen'
+gem 'kitchen-vagrant'
+gem 'kitchen-inspec'
 gem 'community_cookbook_releaser'
diff --git a/recipes/source.rb b/recipes/source.rb
index 7c5a451..fb5d678 100644
--- a/recipes/source.rb
+++ b/recipes/source.rb
@@ -44,7 +44,7 @@ src_filepath = "#{Chef::Config['file_cache_path']}/nginx-#{node['nginx']['source
 package value_for_platform_family(
   %w(rhel fedora amazon) => %w(pcre-devel openssl-devel tar),
   %w(suse) => %w(pcre-devel libopenssl-devel tar),
-  %w(debian) => %w(libpcre3 libpcre3-dev libssl-dev tar)
+  %w(debian) => %w(libpcre3 libpcre3-dev libssl-dev tar zlib1g)
 )
 
 remote_file 'nginx source' do
```
 
And verify:
```
$ bundle exec kitchen verify source-debian-9
-----> Starting Kitchen (v1.19.2)
-----> Setting up <source-debian-9>...
       Finished setting up <source-debian-9> (0m0.00s).
-----> Verifying <source-debian-9>...
       Loaded tests from {:path=>".tmp.nginx.test.integration.source"} 

Profile: tests from {:path=>"/tmp/nginx/test/integration/source"} (tests from {:path=>".tmp.nginx.test.integration.source"})
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Command ps
     ✔  -ef | grep ngin[x] exit_status should eq 0
  Command curl
     ✔  http://localhost/ exit_status should eq 0

Test Summary: 2 successful, 0 failures, 0 skipped
       Finished verifying <source-debian-9> (0m1.05s).
-----> Kitchen is finished. (0m1.68s)

```

**Comment by DavidSie** [comment]
That's true, I tried to fix the error. But it didn't help. Error is not related to a new feature.
I may try to test  it with `zlib1g` package if I have time.

**Comment by tas50** [comment]
There's a few things to do to clean this up, but I'll handle that since I let this languish for so long. Thanks for putting this together. I'm sure a bunch of people will find this pretty useful.

**Pull request merged**
