### PR TITLE
Update build-essential constraint to allow 3.x

### PR DESCRIPTION
**Pull request by scotthain**
This change is [Reviewable](https://reviewable.io/reviews/miketheman/nginx/404)

### CODE REVIEW

**Comment by rhass** [comment]
:shipit:

**Comment by scotthain** [comment]
As a side note - the major version bump of build-essential was to address any breaking issues on Windows based platforms, which should have no effect on the nginx cookbook.

**Comment by tas50** [comment]
@miketheman This it would be really great to get this one merged now that we have a 3.X build-essential release with some significant fixes and improvements

**Comment by miketheman** [comment]
The main branch of this cookbook no longer promotes using Chef configuration management code to **build nginx from scratch** - that is a responsibility that should be done at "build time" - and installation should be done via packages/rsync/whatever to a binary distribution.
The ohai plugins, the build dependencies, compile-time plugins - all made this cookbook too hard to work with, as acknowledged by original maintainers - so the rewrite to provide resources is what this cookbook is aiming to do.

**Comment by scotthain** [comment]
@miketheman totally understand the reasoning behind the rewrite, that's awesome. The issue is that we have a cookbook pinned to 2.x.x and want to bring in the build-essential 3.x code. We were hoping to just get a patch release of the 2.7.x branch with the updated build-essential pinning.

**Comment by schisamo** [comment]
It would be really awesome if we can get this merged and a `2.7.7` published to supermarket. We are currently working off of an internal fork that does just this. This is obviously a real pain.

**Comment by arnaud036** [comment]
+1

**Comment by tas50** [comment]
#418 is the ideal fix for this problem @scotthain

**Comment by tas50** [comment]
#422 is actually the ideal fix as it includes #422

**Comment by tas50** [comment]
This particular issue has been pulled into the chef_nginx cookbook 2.8.0 release. The chef_nginx cookbook is a fork of this cookbook with many of the outstanding issues in the 2.7.6 release resolved. The release is backwards compatible with this cookbook outside of the name change, which obviously requires updating runlist and and metadata dependencies. I'd highly suggest giving it a try to see if this resolves you nginx cookbook woes.

https://github.com/chef-cookbooks/chef_nginx
https://supermarket.chef.io/cookbooks/chef_nginx#changelog

**Comment by tas50** [comment]
Thanks for opening this PR. With the merge of the chef_nginx codebase back into the nginx cookbook I believe it’s no longer necessary. I’m going to close this out now, and I hope you can check out the massive changes that landed on master here #435

**Pull request closed without merging**
