### PR TITLE
Release 2.8.0 with critical fixes + testing improvements

### PR DESCRIPTION
**Pull request by tas50**
This gets us a working 2.X release before shifting gears to 3.X completely. It rolls up a few simple, but incredibly important fixes that have been causing a lot of pain for customers and the community as a whole. It also updates testing with addition platforms, inspec, a simplified rakefile, and cookstyle.

---

This change is [Reviewable](https://reviewable.io/reviews/miketheman/nginx/422)

### CODE REVIEW

**Comment by iennae** [comment]
👍

**Comment by JorisAndrade** [comment]
👍

**Comment by predominant** [comment]
@JorisAndrade If this PR is like any of the others, it will go unnoticed, and unmerged for months. And we'll see the spawn of nginx-ng and nginx2, not to mention nginx-ng2 type cookbooks.

If the supermarket and berkshelf supported namespacing, we could avoid this by having the community naturally carry on enhancements and development on a fork.

As it is, a well established cookbook that ends up being abandoned is really difficult to get moving again, and most likely requires a name change. Not ideal.

**Comment by tas50** [comment]
@predominant Unfortunately it does appear that we won't be able to get this pull request merged. We've chosen instead to pull this branch and PR into our chef-cookbooks org and continue work on it there. This cookbook has been released as chef_nginx. Obviously this less than ideal as you stated above, but I think a Chef maintained version of the cookbook will live on even if individual maintainers come and go. I'd highly recommend everyone check out that new cookbook. It solves the issues above and includes some improved testing and updates. I plan to release a 3.0 version soon that support Chef 12+ only and then work towards adding custom resources to make writing wrapper cookbooks easier. 

https://supermarket.chef.io/cookbooks/chef_nginx
https://github.com/chef-cookbooks/chef_nginx

**Comment by tas50** [comment]
Closing this in favor of a full merge of chef_nginx back into the cookbook

**Pull request closed without merging**
